#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 10/21/17 8:19 PM
# @Author  : Ethan
# @Site    : 
# @File    : main.py.py
# @Software: PyCharm

from scrapy.cmdline import execute

import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
execute(["scrapy", "crawl", "zhihu"])